export const RESUME_DATA = {
  education: [
    {
      school: "University of Maryland, College Park",
      link: "https://umd.edu",
      title:
        "Bachelor's Degree in Computer Science (minor: Technology Entrepreneurship and Corporate Innovation)",
      badges: [
        "Object Oriented Programming",
        "Advanced Data Structures",
        "Algorithms",
        "Computer Systems",
        "Calculus",
        "Linear Algebra",
        "Discrete Structures",
        "Weather and Climate Systems",
        "Web Development",
        "Functional Programming",
        "Parallel Computing",
      ],
      start: "2022",
      end: null,
    },
  ],
  work: [
    {
      company: "BBYO",
      link: "https://azabbg.bbyo.org/",
      location: "Washington, DC",
      badges: [
        "Airtable",
        "Next.js",
        "Vercel",
        "Typescript",
        "Azure",
        "Heroku",
      ],
      title: "AZA & BBG Operations Intern",
      description:
        "Created a summer recruitment algorithm for pinpointing high-potential prospects. Pioneered an internal tool hub for operational efficiency.",
      start: "Aug 2023",
      end: null,
    },
    {
      company: "MooseTrivia",
      link: "https://x.com/triviamoose",
      location: "Remote",
      badges: ["Express.js", "Websockets", "MongoDB", "Heroku"],
      title: "Full Stack Developer",
      description:
        "Elevated user experience through coding, designing, and daily maintenance of a website serving 1,000+ paying users. Established direct websocket connections for real-time updates.",
      start: "May 2020",
      end: "Apr 2023",
    },
    {
      company: "BBYO",
      link: "https://azabbg.bbyo.org/",
      location: "Baltimore, MD",
      badges: ["Airtable", "Heroku", "JavaScript"],
      title: "International Vice President of Finance (Graph Aleph Gizbor)",
      description:
        "Served on the Teen Board of Directors reaching 60+ countries and 80,000+ teens yearly. Oversaw and advised 40+ Regional VPs of Finance in fundraising, philanthropy, budgeting, and finances.",
      start: "Feb 2021",
      end: "June 2022",
    },
  ],
  skills: [
    "JavaScript/TypeScript",
    "Python",
    "Java",
    "C/C++",
    "OCaml",
    "Rust",
    "CUDA",
    "OpenMP",
    "MPI",
    "MATLAB",
    "HTML/CCS",
    "Express.js",
    "React/Next.js",
    "Tailwind CSS",
    "REST APIs",
    "Websockets",
    "Git",
    "MongoDB",
    "Vercel/Heroku",
    "Charles Proxy",
    "Postman",
    "Airtable",
    "Adobe Cloud Suite",
  ],
};
